name: Deploy GKE Infrastructure

on:
  repository_dispatch:
    types: [deploy-infrastructure]

env:
  TF_VERSION: '1.5.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan \
          -var="project_id=${{ github.event.client_payload.project_id }}" \
          -var="region=${{ github.event.client_payload.region }}" \
          -var="cluster_name=${{ github.event.client_payload.cluster_name }}" \
          -var="node_count=${{ github.event.client_payload.node_count }}" \
          -out=tfplan

    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve tfplan